---
# Tasks for java
  
  - name: Installing prerequisites for java
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages: 
      - software-properties-common
      - apt-transport-https

  - name: Adding Java 8 PPA repository
    apt_repository:
      repo: ppa:webupd8team/java
      update_cache: yes

  - name: Accepting oracle licence for java 8 installer
    debconf:
      name: "oracle-java-8-installer"
      question: "shared/accepted-oracle-license-v1-1"
      value: "true"
      vtype: "select"

  - name: Installing Java 8
    apt:
      name: oracle-java8-installer
      force: yes
      update_cache: yes

