---
- name: Prerequisites for setting up DB are installed
  apt:
    name: [ postgresql-client-common ]

- name: DB user for Fimetis is created
  shell: createuser -s {{ fimetis_user }}
  become: yes
  become_user: postgres

- name: Create database for fimetis
  shell: createdb -O {{ fimetis_user }} {{ fimetis_db_name }}
  become: yes
  become_user: postgres

- name: Fimetis database schema is created
  shell: "psql -f {{ fimetis_root }}/src/backend/sql/init.sql"
  become_user: "{{ fimetis_user}}"
  become: yes

- name: Basic database content is populated
  shell: "psql -f {{ fimetis_root }}/src/backend/sql/{{ item }}"
  become_user: "{{ fimetis_user}}"
  become: yes
  loop:
    - filter.sql
    - cluster.sql

#- name: OIDC groups are set in the database
#  shell: psql postgresql://{{ fimetis_db_user }}:{{ fimetis_db_passwd }}@localhost/{{ fimetis_db_name }} -c '{{ item }}'
#  loop:
#    - INSERT INTO "group" (name, urn, role) VALUES({{ oidc_user_group_name }}, {{ oidc_user_group_urn }}, "user");
#    - INSERT INTO "group" (name, urn, role) VALUES({{ oidc_admin_group_name }}, {{ oidc_admin_group_urn }}, "admin");
