---
  - name: Installing postgresql
    apt:
      pkg:
      - postgresql
      - postgresql-contrib
      update_cache: yes

  - name: postgresql is started and enabled upon boot
    service:
      name: postgresql
      enabled: true
      state: started
