---
  - name: Installing postgresql
    apt:
      pkg:
      - postgresql
      - postgresql-contrib
      update_cache: yes

  - name: Starting and setting running postgresql after boot
    systemd:
      name: postgresql
      daemon_reload: yes
      enabled: yes
      state: started
