---
# Tasks for loading testing data

  - name: Creating folder for uploading script
    file:
      path: /opt/metadata-uploader
      state: directory

  - name: Placing uploading script metadata-uploader
    copy:
      src: "{{ role_path }}/files/metadata-uploader.py"
      dest: /opt/metadata-uploader/

  - name: Placing testing data file to machine
    copy:
      src: "{{ role_path }}/files/test.mac"
      dest: /opt/metadata-uploader  

  - name: Loading data to elastic
    shell: source /opt/backend/venv/bin/activate && python3 /opt/backend/import_metadata.py test /opt/metadata-uploader/test.mac  
    args:
      executable: /bin/bash

  - name: Loading testing filter to elastic
    shell: 'curl -XPOST ''localhost:{{ elastic_localhost_port }}/filter/typename'' -H ''Content-Type: application/json'' -d ''{ "name": "select all", "type": "template", "json": "{\"match_all\": {}}"}'''

  - name: Setting size of maximal result from elastic indexes with curl
    shell: 'curl -XPUT ''localhost:{{ elastic_localhost_port }}/_all/_settings?preserve_existing=true'' -H ''Content-Type: application/json'' -d ''{"index.max_result_window" : "20000000"}'''
    args:
      warn: false 

