---

# Tasks for build angular app
  
  - name: Downloading installation script for nodejs
    shell: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    args:
      warn: false

  - name: Installing nodejs
    apt: 
      name: nodejs
      update_cache: yes

  - name: Installing angular 
    command: npm install -g @angular/cli
    become: true

  - name: Downloading repo from gitlab 
    shell: git clone -b 52-suspicious-file-changes-project-init-continuation-of-timeline-forensix --single-branch https://ouath2:pNDgUXuui5kznGnn2_-p@gitlab.ics.muni.cz/kypo2/kypo2-analytical-node.git
    args: 
      chdir: /tmp

  - name: Moving angular app code to /tmp
    shell: mv /tmp/kypo2-analytical-node/methods/analysis/file_system_analysis/frontend/angular /tmp --backup=numbered

  - name: Cleaning nonused source codes from downloaded repo
    file:
      path: /tmp/kypo2-analytical-node
      state: absent

  - name: Set backend api url
    lineinfile:
      path: /tmp/angular/src/environments/environment.prod.ts
      regexp: "^.*backendUrl.*"
      line: "    backendUrl{{':'}} 'http{{':'}}//{{ inventory_hostname}}{{':'}}{{ backend_port }}'"

  - name: Install npm in angular app
    shell: npm install
    args:
      chdir: /tmp/angular

  - name: Building production build of angular app
    shell: ng build --prod
    args:
      chdir: /tmp/angular

  - name:  Placing build app to /opt/
    shell: mv /tmp/angular/dist/fimetis-angular /opt/

  - name: Cleaning source codes from /tmp
    file:
      path: /tmp/angular
      state: absent
    
