---
- hosts: all
  remote_user: ubuntu
  become: yes

  vars_files:
    - ansible-conf.yml

  pre_tasks:
    - name: Check we're on expected OS
      assert:
        that:
          - ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"
        msg: "Ubuntu 20.04 is required at the moment"

    - name: Make sure Python is available
      raw: "{{ item }}"
      loop:
        - sudo apt-get update
        - sudo apt-get -y install python3

  roles:
  - { role: elasticsearch }
  - { role: angular }
#  - { role: kibana }
  - { role: nginx }
  - { role: flask }
  - { role: postgres }
  - { role: upload-data }
