---
- hosts: all
  strategy: free
  vars_files:
    - ansible-conf.yml

  roles:
  - { role: java }
  - { role: elasticsearch }
  - { role: angular }
#  - { role: kibana }
  - { role: nginx }
  - { role: flask }
  - { role: postgres }
  - { role: upload-data }
