---
# Tasks for loading testing data

  - name: Placing testing data file to machine
    copy:
      src: "{{ role_path }}/files/test.mac"
      dest: /opt/metadata-uploader  
 
  - name: Loading testing data to elastic
    shell: /opt/metadata-uploader/metadata-uploader.sh -c test -h localhost:9200 -i metadata -t mactimes -u elastic -p timesix-elk -tp /opt/metadata-uploader/logstash-template.txt /opt/metadata-uploader/test.mac

  - name: Loading testing filter to elastic
    shell: 'curl -XPOST ''localhost:9200/filter/typename'' -H ''Content-Type: application/json'' -d ''{ "name": "select all", "type": "template", "json": "{\"match_all\": {}}"}'''

 
